### PR TITLE
dataset MNIST

### PR DESCRIPTION
**Pull request by geek-yang**
Create a notebook to prepare the MNIST dataset for XAI experiments, including a method to create binary subset of MNIST (e.g. 0 & 1).

### CODE REVIEW

**Comment by elboyran** [comment]
Maybe make a more descriptive title of the Notebook and put the copyright text under in smaller font?
Also, shall we agree that all notebooks should have such a "header"?

**Comment by egpbos** [comment]
Interesting, I've never seen a copyright statement in notebooks before, or perhaps I just never noticed. If we're going to do this structurally, maybe we should also include licensing info.

**Comment by elboyran** [comment]
Now, since you mention it @egpbos , indeed I haven't seen this before either. @geek-yang from where did you adopt this style or is it yours original? ;-)

**Comment by geek-yang** [comment]
Thanks for the comments @elboyran @egpbos. I will rename the notebook to make it more self-explainable. The copy-right thing is indeed a bit bizarre. I can't remember where do I see it for the first time (but I'm sure that the idea comes from one script I saw in our center) but I agree that this can be removed as we already got the license chosen for the whole repository. Therefore it makes no sense.

**Review by elboyran — CHANGES_REQUESTED** [review]
Fixing the title and maybe adding the copyright to the header or removing it.

**Pull request merged**
