### PR TITLE
Added Geometric Shapes generation with parameter variations

### PR DESCRIPTION
**Pull request by WillemSpek**

### CODE REVIEW

**Review by elboyran — CHANGES_REQUESTED** [review]
Hi @WillemSpek , nice that you've found your way in this practical task! 
I see two more things missing, namely:
1 we wound like to order the shapes by the varying parameter to make structured experiments, Especially as it's all in one big nzp file!
2. we should upload the ordered set in the SurfDrive like our other data,

**Comment by WillemSpek** [comment]
I have included the changes, only point is that the data is stored as 1D array, I was uncertain if you wanted it with multiple dimensions.

**Review by elboyran — CHANGES_REQUESTED** [review]
Hi @WillemSpek , nice work! I have 2 remarks:
1. I'm not sure all triangle shapes are saved:

`nvariations = 10
ncircle = nvariations ** 2
ntriangle = nvariations ** 3`, 

but later

`circles = shapes[:ncircle]
triangles = shapes[ncircle:]
...
np.savez_compressed('shapes.npz', circles=circles, triangles=triangles,...`

2. I prefer all research work we do now to be under the folder `dianna-exploration/relevance_maps_properties/.` Can you, please, move the notebook under that folder in subfolder e.g. `test_data`?

**Comment by WillemSpek** [comment]
Hi @elboyran ,

1. all shapes should be saved as `triangles = shapes[ncircle:]` should incude all other shapes aside from the circles, I guess this could be made more explicit.
2. I will move the work to `dianna-exploration/relevance_maps_properties/` under new directory `research_data` or `test_data`.

**Comment by elboyran** [comment]
> Hi @elboyran ,
> 
>     1. all shapes should be saved as `triangles = shapes[ncircle:]` should incude all other shapes aside from the circles, I guess this could be made more explicit.

It is maybe then redundant to introduce ntriangle as not sure it's used. Will check the notebook again.
> 
>     2. I will move the work to `dianna-exploration/relevance_maps_properties/` under new directory `research_data` or `test_data`.

Nice!

**Review by elboyran — APPROVED** [review]
Nice, now images ready to play with! ; - )

**Pull request merged**
